modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="mysubmod"
version="1.0.0"
authors="Olivier Lafontaine"
description='''Mon mod test pour Forge 1.20.1'''

[[mixins]]
config="mysubmod.mixins.json"

[[dependencies.mysubmod]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.mysubmod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
